@startuml filterGames
actor Customer
boundary "Website" as system
control "REST API" as API
control "Database" as db
Customer -> system: Filter by Condition
activate system
system -> API : HTTP get method to get a array of games
activate API
API-->db:Get information about a game with a certain condition
activate db
db--> API: retrive games by query
deactivate db
API-> system:Show results of the users condition
deactivate API
system -> system:showcase the video games that met the users condition
deactivate system
@enduml
